### ISSUE TITLE
Playing directly to output

### ISSUE THREAD

**Issue by mscdex** [chris-rudmin/DecodeToWav#2]
First off, I want to say thanks for the opus encoder example, it works great.

I'm having a problem though playing back the encoded data back to the AudioContext with the decoder. The problem is I cannot find how to determine the correct value for the second argument for `audioContext.createBuffer()`. I'm calling this once for the entire audio recording, so it's supposed to be the number of samples (I think). Currently I'm doing something like this:

```javascript
var pcm = [];

decoderWorker.onmessage = function(e) {
  if (e.data === null)
    playPCM();
  else
    pcm.push(e.data[0]); // Float32Array
};

decoderWorker.postMessage({
  command: 'init',
  decoderSampleRate: 8000,
  outputBufferSampleRate: audioContext.sampleRate
});

// Use copy so the original can be uploaded later
var pages = new Uint8Array(recording);
decoderWorker.postMessage({
  command: 'decode',
  pages: pages
}, [pages.buffer] );

decoderWorker.postMessage({
  command: 'done'
});

function playPCM() {
  if (pcm.length) {
    // `audioContext.sampleRate * pcm.length` is obviously not right ...
    var myArrayBuffer = audioContext.createBuffer(1, audioContext.sampleRate * pcm.length, audioContext.sampleRate);
    var nowBuffering = myArrayBuffer.getChannelData(0);
    for (var p = 0, b = 0; p < pcm.length; ++p) {
      var chunk = pcm[p];
      for (var i = 0; i < chunk.length; ++i,++b)
        nowBuffering[b] = chunk[i];
    }
    var source = this.currentSource = audioContext.createBufferSource();
    source.onended = function() {
      console.log('onended');
    };
    source.buffer = myArrayBuffer;
    source.connect(audioContext.destination);
    source.start(0);
  }
}
```

Is it a matter of passing some extra data from the worker or ?

**Comment by chris-rudmin** [comment]
It is not quite clear to me what you are trying to achieve. Does this [MDN reference](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createBuffer) help solve your problem

**Comment by mscdex** [comment]
In this case, `audioContext.sampleRate === 44100`.

**Comment by chris-rudmin** [comment]
@mscdex A few things:
- I would not specify `decoderSampleRate` so that you decode at the native rate. This might eliminate your noise.
- You need to know the decoder buffer length. The default it is 4096. 
- You will need to know the number of buffers you receive from the decoder. Add a counter in `decoder.onMessage`.
- The total buffer length to specify in `audioContext.createBuffer` will be `number of buffers received * decoder buffer length`.

**Comment by mscdex** [comment]
Setting the total buffer length as you described seems to work, thanks!
