### ISSUE TITLE
Decoded audio has static

### ISSUE THREAD

**Issue by mscdex** [chris-rudmin/DecodeToWav#3]
Using the code I posted in #2, I noticed that when the decoded audio plays, I can hear static in the audio. It doesn't make the recording inaudible, but it is noticeable and gives an unrealistic impression of the actual opus audio quality. If I play back the opus data using the audio tag method in your encoder example, there is no such static.

Any idea?

**Comment by chris-rudmin** [comment]
It is likely because the `decoderSampleRate` is configured to 8000 hz.  The resampler I have written does not do any pre or post filtering so you will get aliasing in the audio band if resampling large ratios.
If you want all audio outside of 8000 hz removed you are probably better to decode at the native rate and then add a filter node in your buffer playback.

**Comment by mscdex** [comment]
The reason for the lower `decoderSampleRate` is that that is what I am encoding to because it's the sample rate I'll be needing when the audio eventually gets uploaded. Playing it back at that rate gives the user a good idea of what their uploaded audio will sound like.

I suppose I could just encode from and to `audioContext.sampleRate` and then decode from that rate to 8000 and play the result? Even if that resolved the static issue, how would I resample the originally encoded opus data before uploading? Doesn't the resampler only work with PCM data, or would I have re-encode by first decoding to `audioContext.sampleRate` and then encode to 8000?

**Comment by chris-rudmin** [comment]
@mscdex If the audio was encoded at a sample rate of 8000, you can decode it at any sample rate, but the bandwidth of the audio will still be at 8000 Hz.  Playing back the decoded audio at 48000 Hz will still only contain the data from reduced sample rate. So in my opinion no additional resampling is required.  My resampler algorithm is not high fidelity so you will introduce some noise and distortion with each additional pass. Best to avoid it if you can.

**Comment by mscdex** [comment]
What I mean is I'm encoding audio recorded from the microphone using `getUserMedia()` and your opus encoder *from* `audioContext.sampleRate` *to* 8KHz. If I then want to play that back so that the user can preview how their recorded audio will sound once it is stored on the server, (as far as I know) I will have to either resample again to something supported by the AudioContext (what I am currently doing) *or* re-encode the data (decode, resample, and then encode, unless there is a way to directly resample encoded opus data) so I can resample it to 8KHz after the user has verified the recording.

**Comment by chris-rudmin** [comment]
Ah I see. In my mind the ideal flow for this is to record at 8KHz and then decode using `outputBufferSampleRate = audioContext.sampleRate` for playback. The playback will be how their recorded audio will sound once stored. When approved upload the original encoded file.

**Comment by mscdex** [comment]
After some more fiddling around I realized I can just change `outputBufferSampleRate` on the decoder from `audioContext.sampleRate` to `8000` and change the third argument to `audioContext.createBuffer()` from `audioContext.sampleRate` to `8000` and it just works! I guess I still have some more learning to do.... Oh well, it's working great now.

Thanks for the quick responses and again for the encoder and decoder!
